-- AlterEnum
ALTER TYPE "DocStatus" ADD VALUE IF NOT EXISTS 'BILLED';
ALTER TYPE "DocStatus" ADD VALUE IF NOT EXISTS 'INVOICED';
ALTER TYPE "DocStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED';

-- AlterTable
ALTER TABLE "VendorBill" ADD COLUMN IF NOT EXISTS "reference" TEXT;
